<?php

namespace Bach\IndexationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository
{

    /**
     * Retrieve published document list
     *
     * @return array
     */
    public function getPublishedDocuments()
    {
        $query = 'SELECT d from BachIndexationBundle:Document d LEFT JOIN d.task t WHERE t.taskId IS NULL or t.status=1';
        $results = $this->getManager()->createQuery($query)->getResult();
        return $results;
    }
}
