# Copyright (c) 2014, Anaphore
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#     (1) Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#
#     (2) Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in
#     the documentation and/or other materials provided with the
#     distribution.
#
#     (3)The name of the author may not be used to
#    endorse or promote products derived from this software without
#    specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

bach_homepage:
    pattern:  /
    defaults: { _controller: BachHomeBundle:Default:index }
    requirements:
        _method: GET

bach_archives:
    pattern: /archives/search/{form_name}/{query_terms}/{page}/{facet_name}
    defaults: { _controller: BachHomeBundle:Default:search, 'form_name': 'default', 'query_terms': null, 'page': 1, 'facet_name': null }
    requirements:
        _method: GET|POST
        page: \d+

bach_search_form_homepage:
    pattern:  /archives/search_form/{form_name}
    defaults: { _controller: BachHomeBundle:Default:search }
    requirements:
        _method: GET

bach_do_search:
    pattern:  /archives/do-search/{form_name}
    defaults: { _controller: BachHomeBundle:Default:doSearch, 'form_name': null }
    requirements:
        _method: POST

bach_browse:
    pattern: /archives/browse/{part}/{ajax}
    defaults: { _controller: BachHomeBundle:Default:browse, part: '', 'ajax': false }
    requirements:
        _method: GET

bach_suggest:
    pattern: /archives/suggest
    defaults: { _controller: BachHomeBundle:Default:doSuggest }
    requirements:
        _method: GET

bach_display_document_paginate:
    pattern: /archives/show/{docid}/{page}/{ajax}
    defaults: { _controller BachHomeBundle:Default:displayDocument, page: 1, ajax: false }
    requirements:
        _method: GET
        page: \d+

bach_display_document:
    pattern: /archives/show/{docid}/{ajax}
    defaults: { _controller BachHomeBundle:Default:displayDocument, ajax: false }
    requirements:
        _method: GET

bach_display_document_rdf:
    pattern: /archives/rdf/{docid}
    defaults: { _controller BachHomeBundle:Default:displayDocumentAsRdf }
    requirements:
        _method: GET

bach_get_cover:
    pattern: /file/covers/{name}
    defaults: { _controller BachHomeBundle:Files:getCover }
    requirements:
        _method: GET
        name: '.+'

bach_get_html_intro_file:
    pattern: /file/intro/{name}
    defaults: { _controller BachHomeBundle:Files:getHtmlIntroFile }
    requirements:
        _method: GET
        name: '.+'

bach_get_file:
    pattern: /file/{type}/{name}
    defaults: { _controller BachHomeBundle:Files:getFile }
    requirements:
        _method: GET
        type: video|music|image|misc
        name: '.+'

bach_fullfacet:
    pattern: /archives/fullfacet/{form_name}/{query_terms}/{name}
    defaults: { _controller: BachHomeBundle:Default:fullFacet }
    requirements:
        _method: GET|POST

bach_geojson:
    pattern: /archives/geojson/{form_name}
    defaults: {_controller: BachHomeBundle:Default:getGeoJson, form_name: null}
    requirements:
        _method: GET

bach_matricules_geojson:
    pattern: /matricules/geojson/{form_name}
    defaults: {_controller: BachHomeBundle:Matricules:getGeoJson, form_name: null}
    requirements:
        _method: GET

bach_add_comment:
    pattern: /comment/{type}/{docid}/add/{ajax}
    defaults: { _controller: BachHomeBundle:Comments:add, ajax: false }
    requirements:
        _method: GET|POST
        type: 'archives|matricules|images'
        docid: '.+'

bach_get_comment:
    pattern: /comment/{type}/{docid}/get
    defaults: { _controller: BachHomeBundle:Comments:get }
    requirements:
        _method: GET
        type: 'archives|matricules|images'
        docid: '.+'

bach_classification:
    pattern: /archives/classification-scheme
    defaults: { _controller: BachHomeBundle:Default:cdc }
    requirements:
        _method: GET

bach_toponym_geoloc:
    pattern: /geoloc/toponym/{name}
    defaults: { _controller: BachHomeBundle:Geoloc:toponym }
    requirements:
        _method: GET
        name: '.+'

bach_raw_geoloc:
    pattern: /geoloc/raw/{name}
    defaults: { _controller: BachHomeBundle:Geoloc:raw }
    requirements:
        _method: GET

bach_store_geoloc:
    pattern: /geoloc/store
    defaults: { _controller: BachHomeBundle:Geoloc:store }
    requirements:
        _method: POST

bach_remove_geoloc:
    pattern: /geoloc/remove/{name}
    defaults: { _controller: BachHomeBundle:Geoloc:remove }
    requirements:
        _method: POST

bach_matricules:
    pattern: /matricules/search/{query_terms}/{page}/{facet_name}
    defaults: { _controller: BachHomeBundle:Matricules:search, 'query_terms': null, 'page': 1, 'facet_name': null }
    requirements:
        _method: GET|POST
        page: \d+

bach_matricules_fullfacet:
    pattern: /matricules/fullfacet/{query_terms}/{name}
    defaults: { _controller: BachHomeBundle:Matricules:fullFacet, form_name: 'default' }
    requirements:
        _method: GET|POST

bach_matricules_do_search:
    pattern:  /matricules-do-search
    defaults: { _controller: BachHomeBundle:Matricules:doSearch }
    requirements:
        _method: POST

bach_matricules_suggest:
    pattern: /matricules/suggest
    defaults: { _controller: BachHomeBundle:Matricules:doSuggest }
    requirements:
        _method: GET

bach_display_matricules:
    pattern: /matricules/show/{docid}/{ajax}/{print}
    defaults: { _controller BachHomeBundle:Matricules:displayDocument, ajax: false, print: false }
    requirements:
        _method: GET

bach_ead_html:
    pattern: /document/{docid}
    defaults: { _controller: BachHomeBundle:Default:eadHtml }
    requirements:
        _method: GET

bach_htmldoc_ext:
    pattern: /archives/htmldoc/{maindir}/{file}.{ext}
    defaults: { _controller: BachHomeBundle:Default:displayHtmlDocumentExt}
    requirements:
        _method: GET
        file: '.+'
        ext: 'js|css|png|gif'

bach_htmlsubdoc:
    pattern: /archives/htmldoc/{maindir}/{file}.{ext}
    defaults: { _controller: BachHomeBundle:Default:displayHtmlSubDocument}
    requirements:
        _method: GET
        ext: 'html|htm'

bach_htmldoc:
    pattern: /archives/htmldoc/{docid}
    defaults: { _controller: BachHomeBundle:Default:displayHtmlDocument}
    requirements:
        _method: GET

dynamic_css:
    pattern: /css/{name}.css
    defaults: { _controller: BachHomeBundle:Default:dynamicCss, _format: css }
    requirements:
        _method: GET

dynamic_js:
    pattern: /scripts/{name}.js
    defaults: { _controller: BachHomeBundle:Default:dynamicJs, _format: js }
    requirements:
        _method: GET

remote_image_infos_nopath:
    pattern: /infosimage/{img}.{ext}
    defaults: { _controller: BachHomeBundle:Default:infosImage, path: null}
    requirements:
        _method: GET
        path: '(.+)?'
remote_image_infos:
    pattern: /infosimage/{path}/{img}.{ext}
    defaults: { _controller: BachHomeBundle:Default:infosImage}
    requirements:
        _method: GET
        path: '(.+)?'
remote_image_infos_noimg:
    pattern: /infosimage/{path}
    defaults: { _controller: BachHomeBundle:Default:infosImage, img: null, ext: null}
    requirements:
        _method: GET
        path: '(.+)?'

remote_matimage_infos_nopath:
    pattern: /matricules/infosimage/{img}.{ext}
    defaults: { _controller: BachHomeBundle:Matricules:infosImage, path: null}
    requirements:
        _method: GET
        path: '(.+)?'
remote_matimage_infos:
    pattern: /matricules/infosimage/{path}/{img}.{ext}
    defaults: { _controller: BachHomeBundle:Matricules:infosImage}
    requirements:
        _method: GET
        path: '(.+)?'
remote_matimage_infos_noimg:
    pattern: /matricules/infosimage/{path}
    defaults: { _controller: BachHomeBundle:Matricules:infosImage, img: null, ext: null}
    requirements:
        _method: GET
        path: '(.+)?'

footer_link:
    pattern: /footer/{type}
    defaults: {_controller: BachHomeBundle:Default:footerLink}
    requirements:
        _method: GET

authorized_cookie:
    pattern: /cookie
    defaults: {_controller: BachHomeBundle:Default:authorizedCookie }
    requirements:
        _method: GET

cookie_link:
    pattern: /cookielink
    defaults: {_controller: BachHomeBundle:Default:cookieLink}
    requirements:
        _method: GET

display_changelog:
    pattern: /displayChangelog
    defaults: {_controller: BachHomeBundle:Files:displayChangelog}
    requirements:
        _method: GET

print_doc:
    pattern: /printDoc/{docid}
    defaults: {_controller: BachHomeBundle:Default:printPdfDoc}
    requirements:
        _method: GET

print_results_page:
    pattern: /printResultsPage/{form_name}/{query_terms}/{page}/{facet_name}
    defaults: { _controller: BachHomeBundle:Default:printPdfResultsPage, 'form_name': 'default', 'query_terms': null, 'page': 1, 'facet_name': null }
    requirements:
        _method: GET|POST
        page: \d+

print_matresults_page:
    pattern: /printMatResultsPage/{form_name}/{query_terms}/{page}/{facet_name}
    defaults: { _controller: BachHomeBundle:Matricules:printPdfMatResultsPage, 'form_name': 'default', 'query_terms': null, 'page': 1, 'facet_name': null }
    requirements:
        _method: GET|POST
        page: \d+

print_matdoc:
    pattern: /printMatdoc/{docid}
    defaults: {_controller: BachHomeBundle:Matricules:printPdfMatdoc}
    requirements:
        _method: GET
