# Copyright (c) 2014, Anaphore
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#     (1) Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#
#     (2) Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in
#     the documentation and/or other materials provided with the
#     distribution.
#
#     (3)The name of the author may not be used to
#    endorse or promote products derived from this software without
#    specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        #facets administration ACLs
        ROLE_SONATA_ARCHIVES_FACETS_READER:
            - ROLE_SONATA_ADMIN_ARCHIVES_FACETS_LIST
            - ROLE_SONATA_ADMIN_ARCHIVES_FACETS_VIEW
        ROLE_SONATA_ARCHIVES_FACETS_EDITOR:
            - ROLE_SONATA_ARCHIVES_FACETS_READER
            - ROLE_SONATA_ADMIN_ARCHIVES_FACETS_CREATE
            - ROLE_SONATA_ADMIN_ARCHIVES_FACETS_EDIT
        ROLE_SONATA_ARCHIVES_FACETS_ADMIN:
            - ROLE_SONATA_ARCHIVES_FACETS_EDITOR
            - ROLE_SONATA_ADMIN_ARCHIVES_FACETS_DELETE
            - ROLE_SONATA_ADMIN_ARCHIVES_FACETS_EXPORT
        #facets administration ACLs (matricules)
        ROLE_SONATA_MATRICULES_FACETS_READER:
            - ROLE_SONATA_ADMIN_MATRICULES_FACETS_LIST
            - ROLE_SONATA_ADMIN_MATRICULES_FACETS_VIEW
        ROLE_SONATA_MATRICULES_FACETS_EDITOR:
            - ROLE_SONATA_MATRICULES_FACETS_READER
            - ROLE_SONATA_ADMIN_MATRICULES_FACETS_CREATE
            - ROLE_SONATA_ADMIN_MATRICULES_FACETS_EDIT
        ROLE_SONATA_MATRICULES_FACETS_ADMIN:
            - ROLE_SONATA_MATRICULES_FACETS_EDITOR
            - ROLE_SONATA_ADMIN_MATRICULES_FACETS_DELETE
            - ROLE_SONATA_ADMIN_MATRICULES_FACETS_EXPORT

        #browse fields administration ACLs
        ROLE_SONATA_ARCHIVES_BROWSEFIELDS_READER:
            - ROLE_SONATA_ADMIN_ARCHIVES_BROWSEFIELDS_LIST
            - ROLE_SONATA_ADMIN_ARCHIVES_BROWSEFIELDS_VIEW
        ROLE_SONATA_ARCHIVES_BROWSEFIELDS_EDITOR:
            - ROLE_SONATA_ARCHIVES_BROWSEFIELDS_READER
            - ROLE_SONATA_ADMIN_ARCHIVES_BROWSEFIELDS_CREATE
            - ROLE_SONATA_ADMIN_ARCHIVES_BROWSEFIELDS_EDIT
        ROLE_SONATA_ARCHIVES_BROWSEFIELDS_ADMIN:
            - ROLE_SONATA_ARCHIVES_BROWSEFIELDS_EDITOR
            - ROLE_SONATA_ADMIN_ARCHIVES_BROWSEFIELDS_DELETE
            - ROLE_SONATA_ADMIN_ARCHIVES_BROWSEFIELDS_EXPORT
        #tag cloud administration ACLs
        ROLE_SONATA_ARCHIVES_TAGCLOUD_READER:
            - ROLE_SONATA_ADMIN_ARCHIVES_TAGCLOUD_LIST
            - ROLE_SONATA_ADMIN_ARCHIVES_TAGCLOUD_VIEW
        ROLE_SONATA_ARCHIVES_TAGCLOUD_EDITOR:
            - ROLE_SONATA_ARCHIVES_TAGCLOUD_READER
            - ROLE_SONATA_ADMIN_ARCHIVES_TAGCLOUD_CREATE
            - ROLE_SONATA_ADMIN_ARCHIVES_TAGCLOUD_EDIT
        ROLE_SONATA_ARCHIVES_TAGCLOUD_ADMIN:
            - ROLE_SONATA_ARCHIVES_TAGCLOUD_EDITOR
            - ROLE_SONATA_ADMIN_ARCHIVES_TAGCLOUD_DELETE
            - ROLE_SONATA_ADMIN_ARCHIVES_TAGCLOUD_EXPORT
        #geoloc administration ACLs
        ROLE_SONATA_GEOLOC_READER:
            - ROLE_SONATA_ADMIN_GEOLOC_LIST
            - ROLE_SONATA_ADMIN_GEOLOC_VIEW
        ROLE_SONATA_GEOLOC_EDITOR:
            - ROLE_SONATA_GEOLOC_READER
            - ROLE_SONATA_ADMIN_GEOLOC_CREATE
            - ROLE_SONATA_ADMIN_GEOLOC_EDIT
        ROLE_SONATA_GEOLOC_ADMIN:
            - ROLE_SONATA_GEOLOC_EDITOR
            - ROLE_SONATA_ADMIN_GEOLOC_DELETE
            - ROLE_SONATA_ADMIN_GEOLOC_EXPORT
        #comments administration ACLs
        ROLE_SONATA_ARCHIVES_COMMENT_READER:
            - ROLE_SONATA_ADMIN_ARCHIVES_COMMENT_LIST
            - ROLE_SONATA_ADMIN_ARCHIVES_COMMENT_VIEW
        ROLE_SONATA_ARCHIVES_COMMENT_EDITOR:
            - ROLE_SONATA_ARCHIVES_COMMENT_READER
            - ROLE_SONATA_ADMIN_ARCHIVES_COMMENT_CREATE
            - ROLE_SONATA_ADMIN_ARCHIVES_COMMENT_EDIT
        ROLE_SONATA_ARCHIVES_COMMENT_ADMIN:
            - ROLE_SONATA_ARCHIVES_COMMENT_EDITOR
            - ROLE_SONATA_ADMIN_ARCHIVES_COMMENT_DELETE
            - ROLE_SONATA_ADMIN_ARCHIVES_COMMENT_EXPORT
        #comments administration ACLs (matricules)
        ROLE_SONATA_MATRICULES_COMMENT_READER:
            - ROLE_SONATA_ADMIN_MATRICULES_COMMENT_LIST
            - ROLE_SONATA_ADMIN_MATRICULES_COMMENT_VIEW
        ROLE_SONATA_MATRICULES_COMMENT_EDITOR:
            - ROLE_SONATA_MATRICULES_COMMENT_READER
            - ROLE_SONATA_ADMIN_MATRICULES_COMMENT_CREATE
            - ROLE_SONATA_ADMIN_MATRICULES_COMMENT_EDIT
        ROLE_SONATA_MATRICULES_COMMENT_ADMIN:
            - ROLE_SONATA_MATRICULES_COMMENT_EDITOR
            - ROLE_SONATA_ADMIN_MATRICULES_COMMENT_DELETE
            - ROLE_SONATA_ADMIN_MATRICULES_COMMENT_EXPORT
        #comments administration ACLs (images)
        ROLE_SONATA_IMAGES_COMMENT_READER:
            - ROLE_SONATA_ADMIN_IMAGES_COMMENT_LIST
            - ROLE_SONATA_ADMIN_IMAGES_COMMENT_VIEW
        ROLE_SONATA_IMAGES_COMMENT_EDITOR:
            - ROLE_SONATA_IMAGES_COMMENT_READER
            - ROLE_SONATA_ADMIN_IMAGES_COMMENT_CREATE
            - ROLE_SONATA_ADMIN_IMAGES_COMMENT_EDIT
        ROLE_SONATA_IMAGES_COMMENT_ADMIN:
            - ROLE_SONATA_IMAGES_COMMENT_EDITOR
            - ROLE_SONATA_ADMIN_IMAGES_COMMENT_DELETE
            - ROLE_SONATA_ADMIN_IMAGES_COMMENT_EXPORT

        #geoloc main fields administration ACLs
        ROLE_SONATA_ARCHIVES_GEOLOCFIELDS_READER:
            - ROLE_SONATA_ADMIN_ARCHIVES_GEOLOCFIELDS_LIST
            - ROLE_SONATA_ADMIN_ARCHIVES_GEOLOCFIELDS_VIEW
        ROLE_SONATA_ARCHIVES_GEOLOCFIELDS_EDITOR:
            - ROLE_SONATA_ARCHIVES_GEOLOCFIELDS_READER
            - ROLE_SONATA_ADMIN_ARCHIVES_GEOLOCFIELDS_CREATE
            - ROLE_SONATA_ADMIN_ARCHIVES_GEOLOCFIELDS_EDIT
        ROLE_SONATA_ARCHIVES_GEOLOCFIELDS_ADMIN:
            - ROLE_SONATA_ARCHIVES_GEOLOCFIELDS_EDITOR
            - ROLE_SONATA_ADMIN_ARCHIVES_GEOLOCFIELDS_DELETE
            - ROLE_SONATA_ADMIN_ARCHIVES_GEOLOCFIELDS_EXPORT
        #geoloc matricules fields administration ACLs
        ROLE_SONATA_MATRICULES_GEOLOCFIELDS_READER:
            - ROLE_SONATA_ADMIN_MATRICULES_GEOLOCFIELDS_LIST
            - ROLE_SONATA_ADMIN_MATRICULES_GEOLOCFIELDS_VIEW
        ROLE_SONATA_MATRICULES_GEOLOCFIELDS_EDITOR:
            - ROLE_SONATA_MATRICULES_GEOLOCFIELDS_READER
            - ROLE_SONATA_ADMIN_MATRICULES_GEOLOCFIELDS_CREATE
            - ROLE_SONATA_ADMIN_MATRICULES_GEOLOCFIELDS_EDIT
        ROLE_SONATA_MATRICULES_GEOLOCFIELDS_ADMIN:
            - ROLE_SONATA_MATRICULES_GEOLOCFIELDS_EDITOR
            - ROLE_SONATA_ADMIN_MATRICULES_GEOLOCFIELDS_DELETE
            - ROLE_SONATA_ADMIN_MATRICULES_GEOLOCFIELDS_EXPORT
        #expos adminsitration ACLs
        ROLE_SONATA_EXPOS_READER:
            - ROLE_SONATA_ADMIN_EXPOS_LIST
            - ROLE_SONATA_ADMIN_EXPOS_VIEW
            - ROLE_SONATA_ADMIN_ROOMS_LIST
            - ROLE_SONATA_ADMIN_ROOMS_VIEW
            - ROLE_SONATA_ADMIN_PANELS_LIST
            - ROLE_SONATA_ADMIN_PANELS_VIEW
            - ROLE_SONATA_ADMIN_DOCUMENTS_LIST
            - ROLE_SONATA_ADMIN_DOCUMENTS_VIEW
        ROLE_SONATA_EXPOS_EDITOR:
            - ROLE_SONATA_EXPOS_READER
            - ROLE_SONATA_ADMIN_EXPOS_CREATE
            - ROLE_SONATA_ADMIN_EXPOS_EDIT
            - ROLE_SONATA_ADMIN_ROOMS_CREATE
            - ROLE_SONATA_ADMIN_ROOMS_EDIT
            - ROLE_SONATA_ADMIN_PANELS_CREATE
            - ROLE_SONATA_ADMIN_PANELS_EDIT
            - ROLE_SONATA_ADMIN_DOCUMENTS_CREATE
            - ROLE_SONATA_ADMIN_DOCUMENTS_EDIT
        ROLE_SONATA_EXPOS_ADMIN:
            - ROLE_SONATA_EXPOS_EDITOR
            - ROLE_SONATA_ADMIN_EXPOS_DELETE
            - ROLE_SONATA_ADMIN_EXPOS_EXPORT
            - ROLE_SONATA_ADMIN_ROOMS_DELETE
            - ROLE_SONATA_ADMIN_ROOMS_EXPORT
            - ROLE_SONATA_ADMIN_PANELS_DELETE
            - ROLE_SONATA_ADMIN_PANELS_EXPORT
            - ROLE_SONATA_ADMIN_DOCUMENTS_DELETE
            - ROLE_SONATA_ADMIN_DOCUMENTS_EXPORT

        ROLE_ARCHIVIST:     [ROLE_USER, ROLE_CONTENT_ADMIN]
        ROLE_CONTENT_ADMIN: [ROLE_SONATA_ARCHIVES_FACETS_EDITOR, ROLE_SONATA_MATRICULES_FACETS_EDITOR, ROLE_SONATA_ARCHIVES_BROWSEFIELDS_EDITOR, ROLE_SONATA_ARCHIVES_TAGCLOUD_EDITOR, ROLE_SONATA_ARCHIVES_GEOLOCFIELDS_EDITOR, ROLE_SONATA_MATRICULES_GEOLOCFIELDS_EDITOR, ROLE_SONATA_EXPOS_EDITOR, ROLE_SONATA_GEOLOC_EDITOR, ROLE_SONATA_ARCHIVES_COMMENT_EDITOR, ROLE_SONATA_MATRICULES_COMMENT_EDITOR, ROLE_SONATA_IMAGES_COMMENT_EDITOR]
        ROLE_ADMIN:         [ROLE_USER, ROLE_ARCHIVIST, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN:   [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        #order matters: if fos is not in the first place, impersonating will fail
        fos_userbundle:
            id: fos_user.user_provider.username
        openid_user_manager:
            id: bach.home.openid_user_manager

    firewalls:
        # Disabling the security for the web debug toolbar, the profiler and Assetic.
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            fp_openid:
                create_user_if_not_exists: true
                login_path: /login
                provider: openid_user_manager
                required_attributes:
                    - namePerson
                    - namePerson/friendly
                    - namePerson/first
                    - namePerson/last
                    - contact/email
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout: true
            anonymous: true
            switch_user: true

        admin:
            pattern:            /admin(.*)
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   null
            logout:
                path:           /admin/logout
            anonymous:          true

    acl:
        connection: default

    access_control:
        # Login pages needs to be access without credential
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_openid$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Secured part of the site
        - { path: ^/admin/, role: [ROLE_ADMIN, ROLE_CONTENT_ADMIN] }
        - { path: ^/admin/sonata, roles: ROLE_SUPER_ADMIN }
        - { path : ^/indexation, roles: ROLE_ARCHIVIST }

