<?php
/**
 * Bach SonatauserBundle
 *
 * PHP version 5
 *
 * @category Administration
 * @package  Bach
 * @author   Johan Cwiklinski <johan.cwiklinski@anaphore.eu>
 * @license  Unknown http://unknown.com
 * @link     http://anaphore.eu
 */

namespace Application\Sonata\UserBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;

/**
 * Bach SonataUserBundle
 * This file has been generated by the Sonata EasyExtends bundle
 * (http://sonata-project.org/bundles/easy-extends)
 *
 * @category Administration
 * @package  Bach
 * @author   Johan Cwiklinski <johan.cwiklinski@anaphore.eu>
 * @license  Unknown http://unknown.com
 * @link     http://anaphore.eu
 */
class ApplicationSonataUserBundle extends Bundle
{
    /**
     * Get Parent
     *
     * @return string
     */
    public function getParent()
    {
        return 'SonataUserBundle';
    }
}
